#!/usr/bin/env node

/**
 * Module dependencies.
 */

var config = require(process.cwd()+'/gulp/gulp.config')();

/**
 * Get port from environment and store in Express.
 */

config.vars.app.use(config.vars.express.static(config.vars.EXPRESS_ROOT));

/**
 * Create HTTP server & Listen on provided port, on all network interfaces.
 */

config.vars.app.listen(config.vars.EXPRESS_PORT);

/**
 * !!!!!!!! Root is already SET in gulp.config.vars !!!!!!!!!!!!!!!
 */


/**
 * Event listener for HTTP server "error" event.
 */

config.vars.app.on('error', onError);
config.vars.app.on('listening', onListening);

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
